name: Fetch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - 'main.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.24.0'

      - name: Fetch Proxy IP list
        run: curl https://zip.baipiao.eu.org > txt.zip

      - name: Generate list
        run: go run . txt.zip

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin main
          git add list.txt
          git commit -m "Update list at $(date '+%Y-%m-%d %H:%M:%S')"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
